[feat] merging
JoaoArrudaWarren/warren-everest-api pull request #1
Opened 2022-09-14 20:24 UTC by JoaoArrudaWarren

2022-09-15 16:41 UTC, LeonardoAlthoff requested changes
Revisar comentários.

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        }
Trocar o retorno para IActionResult, pois trata-se da interface que contempla todos os ActionResult.

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        [HttpGet("GetSpecificFromList")]
A nomenclatura das rotas deve ser tudo em minúsculo com separação das palavras por "-".

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        public virtual List<Customer> GetAll()
Como estamos na controller, o método não deve ser virtual, pois não será reescrito por outra classe.

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +            model.Cpf = model.Cpf.Trim().Replace(".", "").Replace("-", "");
Prefira fazer essa validação diretamente no construtor da classe model. O Card indica que o salvamento do cpf deve ser feito ser os caracteres ".", "-" ou ".", portanto ele deve ser tratado em qualquer instância da classe.

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/Customer.cs
> +    }
Aqui, criar construtor com a formatação do CPF com method extension.

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +            RuleFor(x => x.Cpf.Trim().Replace(".", "").Replace("-", "")).MinimumLength(10).MaximumLength(14).Must(BeAValidCpf).
Com a  formatação no construtor, não há necessidade dessa regra aqui, tampouco a validação do tamanho da string. Não precisa colocar o NotNull, pois o NotEmpty é uma evolução dele e já confere se o campo é nulo. Por fim, uma vez que você construiu um validador de CPF, não é preciso conferir o tamanho da string.

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +            RuleFor(x => x.Number).NotEmpty().WithMessage("This is required");
Retornar a mensagem com o campo específico que não passou na validação.

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +
Retirar após a formatação diretamente no construtor
```suggestion

```

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +
A fórmula padrão não exclui cpfs como "111.111.111-11". É possível realizar a exclusão com o seguinte código: 
```suggestion
                if (cpf.Length != 11) return false;
                if(cpf.All(x => x == cpf.First())) return false;

```

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/ListCustomer.cs
> +}
Não é necessário criar uma classe inteira para a lista. Basta instanciá-la no CustomerRepository como "private readonly List<Customer> list = new();

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/RepositoryList.cs
> +            }
Sua lógica de auto incrementar IDs está meio quebrada

Exemplo:
Lista com os IDs: 1, 2, 3, 4; count = 4,
Adicionar novo customer: next id = count + 1 = 5
Resultado = 1, 2, 3, 4, 5
Até aí tudo bem, irá adicionar um novo ID sem problemas

Se eu deletar um customer e depois adicionar um novo, ficará assim: (Customer deletado: id = 1)
Lista com os IDs: 2, 3, 4, 5; count = 4;
Adicionar novo customer: next id = count + 1 = 5
Resultado = 2, 3, 4, 5, 5
O ID = 5 se repete

Se eu deletar novamente um customer e depois adicionar um novo... (Customer deletado: id = 2)
Lista com os IDs: 3, 4, 5, 5; count = 4;
Adicionar novo customer: next id = count + 1 = 5
Resultado = 3, 4, 5, 5, 5
O ID = 5 se repete

Resultado Final => IDs: 3, 4, 5, 5, 5; count = 5
Não podemos repetir ID, pois é um identificador individual.
```suggestion
  model.Id = list.LastOrDefault()?.Id + 1 ?? 1;
```

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/RepositoryList.cs
> +        }
Considerando que há um delete com o ID, não acho que seja necessário um com o cpf e email. De todo modo, é possível melhorar a eficiência do código com as funções nativas da lista.

2022-09-15 16:41 UTC, LeonardoAlthoff commented on ApiFirst/ApiFirst/RepositoryList.cs
> +            return 404;
Aqui só há dois retornos: Ok ou NotFound. É melhorar a exclusão com a função abaixo:
```suggestion
            var index = list.FindIndex(customer => customer.Id == id);
            if(index == -1) return 404;
            list.RemoveAt(index);
            return 200;
```

2022-09-15 17:04 UTC, ghost commented on ApiFirst/ApiFirst/ApiFirst.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
```suggestion
  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
```

2022-09-15 17:04 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/BaseModel.cs
> +        [Key]
```suggestion
namespace DomainModels.Models
{
    public abstract class BaseModel
    {
```

2022-09-15 17:04 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        [HttpDelete("DeleteFromList")]
```suggestion
        [HttpDelete]
```

2022-09-15 17:05 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        public ActionResult DeleteFromList([FromQuery] string cpf, string email)
Delete deve ser feito via Id

2022-09-15 18:44 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        }
É service ou repository?
```suggestion
        private readonly ICustomerRepository _customerRepository;

        public CustomersController(ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository?? throw new ArgumentNullException(nameof(customerRepository));
        }
```

2022-09-15 18:45 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        }
É redundante ter get na rota porque o endpoint já é get
```suggestion
        [HttpGet("cpf")]
        public Customer? GetByCpf([FromQuery] string cpf)
        {
            return _service.GetByCpf(cpf);
        }
```

2022-09-15 18:50 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        public Customer? GetByCpf([FromQuery] string cpf)
1. É redundante ter get na rota porque o endpoint já é get
2. É um parâmetro obrigatório então ser enviado via rota e não query

```suggestion
        [HttpGet("cpf/{cpf}")]
        public Customer? GetByCpf(string cpf)
```

2022-09-15 18:50 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        [HttpGet("get-all")]
É redundante ter get na rota porque o endpoint já é get
```suggestion
        [HttpGet]
```

2022-09-15 18:51 UTC, ghost commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        }
É um parâmetro obrigatório então ser enviado via rota e não query
```suggestion
        [HttpGet("{id}")]
        public Customer? GetById(int id)
        {
            return _service.GetById(id);
        }
```

2022-09-15 18:53 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        public IActionResult Delete(int id)
É um parâmetro obrigatório então ser enviado via rota e não query
```suggestion
        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
```

2022-09-15 18:56 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        public IActionResult Update(string cpf, Customer model)
Todo update em banco deve usado Id pois é único campo confiável e imutável

2022-09-15 19:07 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        public IActionResult Update(string cpf, Customer model)
Está fazendo Patch e está mandando todos os campos? isso é Update, não faz sentido ser um patch

2022-09-16 12:51 UTC, AlanmWarren commented on ApiFirst/ApiFirst/RepositoryList.cs
> +    public class RepositoryList : ICustomerRepository
```suggestion
    public class CustomerService : ICustomerService
```
Renomear para `CustomerService` e sua interface, `ICustomerService`

2022-09-16 12:55 UTC, AlanmWarren commented on ApiFirst/ApiFirst/RepositoryList.cs
> +        private readonly List<Customer> List = new();
```suggestion
        private readonly List<Customer> _customers = new();
```
Usar IList e ajustar nome da lista para `_customers`

2022-09-16 13:00 UTC, AlanmWarren commented on ApiFirst/ApiFirst/RepositoryList.cs
> +            model.Id = GetAll().LastOrDefault()?.Id + 1 ?? 0;
```suggestion
            model.Id = _customers.LastOrDefault()?.Id + 1 ?? 1;
```
Usar a lista renomeada comentada anteriormente e ajustar a lógica de ID, para quando retornar nulo (Quando não existir nenhum usuário para pegar o último ID criado) o ID do usuário seja 1,

2022-09-16 13:02 UTC, AlanmWarren commented on ApiFirst/ApiFirst/RepositoryList.cs
> +            bool exist = GetAll().Any(customer => customer.Cpf == model.Cpf || customer.Email == model.Email);
```suggestion
            bool exist = _customers.Any(customer => customer.Cpf == model.Cpf || customer.Email == model.Email);
```
Podemos fazer essa validação em um método separado e chamá-lo aqui. Usar a lista ao invés do método GetAll()

2022-09-16 13:05 UTC, AlanmWarren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +                return NotFound($"Não foi encontrado Costumer para o Id: {id}");
```suggestion
                return NotFound($"Não foi encontrado Customer para o Id: {id}");
```

2022-09-16 13:06 UTC, AlanmWarren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +            return Ok(response);
Recomendo uso de if ternário

2022-09-19 13:36 UTC, AlanMDomingues commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +        public ActionResult<Customer?> GetById(int id)
```suggestion
        public IActionResult<Customer?> GetById(int id)
```

2022-09-19 13:36 UTC, AlanMDomingues commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +            var response = _customerService.GetById(id);
```suggestion
        {
            var response = _customerService.GetById(id);
```

2022-09-19 13:36 UTC, AlanMDomingues commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +                : BadRequest("O Email ou CPF já é usado.");
```suggestion
                : BadRequest("O Email ou CPF já existem.");
```

2022-09-19 13:36 UTC, AlanMDomingues commented on ApiFirst/ApiFirst/Customer.cs
> +        }
```suggestion
        public Customer(
        string fullName,
        string email,
        string emailConfirmation,
        string cpf,
        string cellphone,
        DateTime dateOfBirth,
        bool emailSms,
        bool whatsapp,
        string country,
        string city,
        string postalCode,
        string address,
        string number
        )
        {
            FullName = fullName;
            Email = email;
            EmailConfirmation = emailConfirmation;
            Cpf = cpf.Trim().Replace(".", "").Replace("-", "");
            Cellphone = cellphone;
            DateOfBirth = dateOfBirth;
            EmailSms = emailSms;
            Whatsapp = whatsapp;
            Country = country;
            City = city;
            PostalCode = postalCode;
            Address = address;
            Number = number;
        }
```

2022-09-19 13:36 UTC, AlanMDomingues commented on ApiFirst/ApiFirst/CustomerService.cs
> +        private readonly List<Customer> _customers = new();
```suggestion
        private readonly IList<Customer> _customers = new();
```

2022-09-19 13:36 UTC, AlanmWarren commented on ApiFirst/ApiFirst/CustomerService.cs
> +            }
Método Patch deveria atualizar apenas campos pré-definidos, não podemos atualizar quantos e quais campos quisermos, já deve estar descrito quais campos vão ser atualizados. Recomendo deixar para fazer esse método depois que começar a usar banco de dados, pois com o EntityFrameworkCore vai ser muito mais fácil. Por enquanto podemos ficar apenas com o método Put

2022-09-19 13:36 UTC, AlanmWarren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +            int result = _customerService.Update(id, model);
```suggestion
            var result = _customerService.Update(id, model);
```

2022-09-19 13:36 UTC, AlanmWarren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +            int result = _customerService.Modify(id, model);
```suggestion
            var result = _customerService.Modify(id, model);
```

2022-09-19 13:36 UTC, AlanmWarren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +                ? CreatedAtAction(nameof(GetById), new { id = model.Id }, model)
```suggestion
                ? Created("", model.Id)
```
Aqui devemos retornar apenas o ID do novo Customer criado

2022-09-19 13:36 UTC, AlanmWarren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +            return _customerService.Create(model)
```suggestion
        {
            var result = _customerService.Create(model);
            return result
```
Primeiro armazenar numa variável o retorno do método. Fazer isso para os outros métodos da controller também

2022-09-19 13:36 UTC, AlanmWarren commented on ApiFirst/ApiFirst/Customer.cs
> +        public string Number { get; set; }
```suggestion
        public int Number { get; set; }
```
Number é do tipo int, conforme descrito no card

2022-09-19 13:36 UTC, AlanmWarren commented on ApiFirst/ApiFirst/CustomerService.cs
> +namespace DomainServices.Repositories
Que namespace é esse? Vi que suas classes não estão com seus namespaces sincronizados

2022-09-19 13:39 UTC, AlanmWarren commented on ApiFirst/ApiFirst/Controllers/CostumersController.cs
> +    public class CustomersController : ControllerBase
Arquivo está nomeado como "CostumersController", renomeie de acordo com essa classe

2022-09-19 15:00 UTC, AlanMDomingues commented on ApiFirst/ApiFirst/Customer.cs
> +        public int Number;
E os get e setters? recomendo deixar as props abaixo do construtor para mais fácil manutenção

2022-09-19 17:04 UTC, AlanmWarren commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +            RuleFor(x => x.Number).NotEmpty().WithMessage("Number is required");
A maioria das validações só são de verificar se é nulo, fazer mais validações

2022-09-20 13:24 UTC, AlanmWarren commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +                WithMessage("Number is required");
Arrumar indentação

2022-09-20 13:38 UTC, AlanmWarren commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +            }
```suggestion
            bool FirstLetterUpperCase(string input) => char.IsUpper(input[0]);
```

2022-09-20 16:38 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/Customer.cs
> +        int number
```suggestion
            string fullName,
            string email,
            string emailConfirmation,
            string cpf,
            string cellphone,
            DateTime dateOfBirth,
            bool emailSms,
            bool whatsapp,
            string country,
            string city,
            string postalCode,
            string address,
            int number
```

2022-09-20 16:39 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomerService.cs
> +            }
```suggestion
            if (Exists(model))
            {
                return false;
            }
            
            _customers.Add(model);
            return true;
            }
```

2022-09-20 16:43 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomerService.cs
> +            int index = _customers.IndexOf(response);
```suggestion
            var index = _customers.FindIndex(customer => customer.Id == id);
```

2022-09-20 16:45 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomerService.cs
> +            int index = _customers.IndexOf(response);
Mesmo caso do comentário acima

2022-09-20 16:45 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomerService.cs
> +            }
```suggestion
            if (!ExistsUpdate(id, model)) return 0;

            model.Id = _customers[index].Id;
            _customers[index] = model;
            return 1;
```

2022-09-20 16:45 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomerService.cs
> +        public int Modify(int id, string email)
O que seria esse modify?

2022-09-20 16:46 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +            RuleFor(x => x.Number).NotEmpty().GreaterThanOrEqualTo(1);
Quebrar linha para cada método em cada um dos RuleFor

2022-09-20 16:46 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +            bool FirstLetterUpperCase(string input)
```suggestion
            bool FirstLetterIsUpperCase(string input)
```

2022-09-20 16:46 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +            bool BeAValidCpf(string cpf)
```suggestion
            bool IsValidCpf(string cpf)
```

2022-09-20 16:47 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +                tempCpf = cpf.Substring(0, 9);
```suggestion
                if (cpf.All(x => x == cpf.First())) return false;

                tempCpf = cpf.Substring(0, 9);
```

2022-09-20 16:47 UTC, viniciusoliveira-warren commented on ApiFirst/ApiFirst/CustomersValidator.cs
> +                char chars = input[0];
```suggestion
                var chars = input.First();
```

2022-09-20 16:49 UTC, JoaoArrudaWarren commented on ApiFirst/ApiFirst/CustomerService.cs
> +            int index = _customers.IndexOf(response);
Este método não existe para IList

2022-09-20 16:51 UTC, JoaoArrudaWarren commented on ApiFirst/ApiFirst/CustomerService.cs
> +        public int Modify(int id, string email)
É um patch,mas sem precisar de todas as verificações. Foi pedido em review que eu alterasse essa implementação

2022-09-20 16:54 UTC, JoaoArrudaWarren commented on ApiFirst/ApiFirst/CustomerService.cs
> +            int index = _customers.IndexOf(response);
Devo retirar a IList e colocar List novamente?

2022-09-20 19:30 UTC, AlanmWarren approved these changes

2022-09-20 19:31 UTC, viniciusoliveira-warren approved these changes

2022-09-20 19:32 UTC, merged